/**
 * Shared definitions for the multi-end compile.
 *
 * `src/` is the only source. `claude/`, `codex/` and `common/` are artifacts in their entirety —
 * every file in them is generated by `scripts/build.ts`. A capability is authored once; the
 * compiler emits one serialization per end.
 *
 * The three ends:
 *   claude — Claude Code plugins, installed and updated through a marketplace
 *   codex  — Codex plugins (no `commands/` concept; agents cannot be bundled by a plugin)
 *   common — the vendor-neutral layout: `.agents/skills/<name>/SKILL.md`, which opencode and
 *            friends discover natively. No plugin wrapper, no manifest.
 *
 * Run with `node scripts/build.ts`: Node ≥22.18 strips the types at load time, so the build stays
 * dependency-free. `typescript` is a devDependency for `tsc --noEmit` and nothing else — which is
 * why `erasableSyntaxOnly` is on in tsconfig.json.
 */

export type End = 'claude' | 'codex' | 'common';

export const ENDS: readonly End[] = ['claude', 'codex', 'common'];

export type Tier = 'top' | 'standard' | 'light';

/**
 * Model tier → the concrete model on each end.
 *
 * Three tiers, because both families ship three: judgement-heavy work that has to be right the
 * first time, ordinary execution, and mechanical work where latency matters more than depth.
 * Naming the tier rather than the model is what lets a role survive a model refresh — the table
 * moves, the roles do not.
 *
 * `common` is deliberately `null`: the vendor-neutral layout has no agreed model field, and the
 * host is the one that knows which providers are configured. Emitting a guess would be worse than
 * emitting nothing — a wrong model id fails at run time, an absent one lets the host decide.
 */
export const TIER: Record<Tier, Record<End, string | null>> = {
  top: { claude: 'opus', codex: 'gpt-5.6-sol', common: null },
  standard: { claude: 'sonnet', codex: 'gpt-5.6-terra', common: null },
  light: { claude: 'haiku', codex: 'gpt-5.6-luna', common: null },
};

export const isTier = (t: string): t is Tier => Object.hasOwn(TIER, t);

/**
 * The per-end root path variable, substituted for `${PLUGIN_ROOT}` in prose.
 *
 * Claude and Codex expose a real variable pointing at the installed plugin directory. The common
 * end has no plugin directory at all — skills live at `.agents/skills/<name>/`, so the closest
 * honest answer is the project-relative `.agents`. Note the limitation: a *globally* installed
 * common skill lives at `~/.agents/`, where a relative path does not resolve. Prose that has to
 * work on the common end should prefer paths relative to the skill's own directory.
 */
export const PLUGIN_ROOT: Record<End, string> = {
  claude: '${CLAUDE_PLUGIN_ROOT}',
  codex: '${CODEX_PLUGIN_ROOT}',
  common: '.agents',
};

const ALT = ENDS.join('|');
/** One `<!--@end-->`-terminated block, whatever ends it names inside. */
const BLOCK_RE = new RegExp(`<!--@(?:${ALT})-->\\n[\\s\\S]*?<!--@end-->\\n?`, 'g');
/** Inside a block: one end's slice, running up to the next marker. */
const SLICE_RE = new RegExp(`<!--@(${ALT})-->\\n([\\s\\S]*?)(?=<!--@(?:${ALT}|end)-->)`, 'g');
/** Any marker at all — used to catch typos and unterminated blocks. */
export const ANY_MARKER_RE = /<!--@([a-z][a-z0-9-]*)-->/g;

/**
 * Variant blocks: the source keeps every end's paragraph, and compilation keeps one.
 * They ride on HTML comments, so the source file stays valid, previewable markdown.
 *
 *   <!--@claude-->
 *   Drive the user's real browser with `claude --chrome`.
 *   <!--@codex-->
 *   Enumerate the browser tools this session actually exposes.
 *   <!--@common-->
 *   Use whatever browser tool the host provides.
 *   <!--@end-->
 *
 * An end a block does not name gets nothing — that is how a paragraph is scoped to a subset of the
 * ends without inventing a second mechanism.
 */
export function applyVariants(text: string, end: End): string {
  return text.replace(BLOCK_RE, (block) => {
    const parts: Partial<Record<End, string>> = {};
    const re = new RegExp(SLICE_RE.source, 'g');
    let m: RegExpExecArray | null;
    while ((m = re.exec(block)) !== null) parts[m[1] as End] = m[2] as string;
    return parts[end] ?? '';
  });
}

/**
 * A block that resolves to nothing still leaves its surrounding blank lines behind, so an end that
 * drops two adjacent blocks ends up with a four-newline hole. Three or more consecutive newlines
 * carry no meaning in markdown prose — but they do inside a fenced code block, so fences are cut
 * out and rejoined untouched.
 */
function collapseBlankRuns(text: string): string {
  return text
    .split(/(^```[\s\S]*?^```$)/gm)
    .map((seg, i) => (i % 2 === 1 ? seg : seg.replace(/\n{3,}/g, '\n\n')))
    .join('');
}

/** Source text → one end's finished text: resolve variant blocks, substitute the root path. */
export function renderFor(text: string, end: End): string {
  const resolved = collapseBlankRuns(applyVariants(text, end));
  return resolved.split('${PLUGIN_ROOT}').join(PLUGIN_ROOT[end]);
}

/**
 * Two failure modes a plain compile would ship silently:
 *   - a typo'd end name (`<!--@opencode-->`) — the block never matches, so the markers and *every*
 *     end's text land in all three artifacts
 *   - a missing `<!--@end-->` — same outcome, different cause
 * Both leave `<!--@` in the rendered output, which is the signature this looks for.
 * @returns human-readable problems; empty when the text is clean
 */
export function lintVariants(text: string): string[] {
  const problems: string[] = [];
  for (const m of text.matchAll(ANY_MARKER_RE)) {
    const name = m[1] as string;
    if (name !== 'end' && !ENDS.includes(name as End)) {
      problems.push(`unknown variant end "${name}" — expected one of ${ENDS.join(' | ')}`);
    }
  }
  for (const end of ENDS) {
    if (renderFor(text, end).includes('<!--@')) {
      problems.push(`a variant marker survives the ${end} render — most likely a missing <!--@end-->`);
    }
  }
  return [...new Set(problems)];
}

export interface Frontmatter {
  /** Values with surrounding quotes unwrapped, for reading. */
  meta: Record<string, string>;
  /** The original spelling, verbatim: quoting is the author's choice, echoed back rather than guessed at. */
  raw: Record<string, string>;
  body: string;
}

/** Minimal frontmatter parsing: `key: value` scalars only, which is all these source files need. */
export function splitFrontmatter(src: string): Frontmatter {
  const m = /^---\n([\s\S]*?)\n---\n([\s\S]*)$/.exec(src);
  if (!m) return { meta: {}, raw: {}, body: src };
  const meta: Record<string, string> = {};
  const raw: Record<string, string> = {};
  for (const line of (m[1] as string).split('\n')) {
    const kv = /^([A-Za-z_][\w-]*):\s*([\s\S]*)$/.exec(line);
    if (!kv) continue;
    const key = kv[1] as string;
    const value = kv[2] as string;
    raw[key] = value;
    if (value.startsWith('"')) {
      try {
        meta[key] = JSON.parse(value) as string;
        continue;
      } catch {
        /* fall through to the raw form */
      }
    }
    meta[key] = value;
  }
  return { meta, raw, body: m[2] as string };
}

/**
 * A description is a **trigger surface**, and every host ranks it by its own retrieval model —
 * the same wording that fires reliably on one model under-triggers on another. So this is the one
 * field expected to be tuned per end rather than shared, and the frontmatter carries a slot per end:
 *
 *   description          the fallback, and what `common` consumes — no host-specific tuning in it
 *   description-claude   overrides it for Claude
 *   description-codex    overrides it for Codex
 *
 * `common` deliberately has no `description-common` slot: it is the vendor-neutral end, so the
 * untuned fallback *is* its description. A `description-common:` key would still resolve (the
 * lookup is generic), but writing one means the fallback has stopped being neutral — tune the two
 * named ends and leave `description` as the thing they diverge from.
 */
export const descriptionFor = (raw: Record<string, string>, end: End): string =>
  raw[`description-${end}`] ?? raw['description'] ?? '';

/**
 * The same lookup against the **parsed** map, for targets that re-serialize the value themselves.
 *
 * The distinction matters and has bitten once. Markdown frontmatter is emitted by echoing the
 * author's own spelling, quotes included, so it reads `raw`. A TOML value is built with
 * `JSON.stringify`, which adds its own quoting — feeding it `raw` wraps an already-quoted string a
 * second time and ships `description = "\"Dispatch this agent…\""` to the artifact.
 */
export const descriptionValueFor = (meta: Record<string, string>, end: End): string =>
  meta[`description-${end}`] ?? meta['description'] ?? '';
